#!/bin/bash

#some reasonable defaults
cpuinfo='/usr/bin/cpufreq-info'
cpuset='/usr/bin/cpufreq-set'
LIST=

#parameter parsing taken from http://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash
while [[ "$#" > 0 ]]
do
key="$1"
case $key in
    -l|--list)
    LIST=YES
    SET=NO
    ;;
    -s|--set)
    SET=YES
    LIST=NO
    ;;
    -f|--frequency)
    FREQUENCY=YES
    ;;
    -q|--quiet)
    QUIET=YES
    ;;
    -g|--governor)
    GOVERNOR="$2"
    shift
    ;;
    -c|--cpu)
    CPU="$2"
    shift
    ;;
    -m|--min)
    MIN="$2"
    shift
    ;;
    -M|--max)
    MAX="$2"
    shift
    ;;
    -h|--help)
    usage;
    exit 0;
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done

#echo "SET: " $SET
#echo "LIST: " $LIST
#echo "GOVERNOR: " $GOVERNOR
#echo "CPU: " $CPU
#echo "MIN: " $MIN
#echo "MAX: " $MAX
#echo "FREQUENCY: " $FREQUENCY

function usage {
	printf "Usage:
$0 [options]

Options:
 -l, --list\t\t\t List a parameter
 -s, --set\t\t\t Set a parameter
 -g, --governor <governor>\t Select a governor (available in cpufreq-info)
 -c, --cpu <number>\t\t The CPU to edit/query. Leave blank for all CPUs
 -m, --min <number>\t\t The minimum CPU frequency (must be supported by governor and CPU. More info in cpufreq-info)
 -M, --max <number>\t\t The maximum CPU frequency (must be supported by governor and CPU. More info in cpufreq-info)
 -f, --frequency\t\t The current CPU frequency
 -q, --quiet\t\t\t Don't display much output when setting a parameter
 -h, --help\t\t\t Show this help screen
"
}

function getCurrentFrequency {
	OPTS="$1"
	local OUTPUT=`$cpuinfo -f $OPTS | sed 's/000$/MHz/'`;
	if [ ! -z "$OUTPUT" ]; then
		echo "$OUTPUT"
	fi
}

function getCurrentGovernor {
	OPTS="$1"
	local OUTPUT=`$cpuinfo -p $OPTS | cut -d " " -f 3`;
	if [ ! -z "$OUTPUT" ]; then
		echo "$OUTPUT"
	fi
}

function getMinFrequency {
	OPTS="$1"
	local OUTPUT=`$cpuinfo -l $OPTS | cut -d " " -f 1 | sed 's/000$/MHz/'`;
	if [ ! -z "$OUTPUT" ]; then
		echo "$OUTPUT"
	fi
}

function getMaxFrequency {
	OPTS="$1"
	local OUTPUT=`$cpuinfo -l $OPTS | cut -d " " -f 2 | sed 's/000$/MHz/'`;
	if [ ! -z "$OUTPUT" ]; then
		echo "$OUTPUT"
	fi
}

function list {
	processor="$1"
	option="$2"
	
#	echo "option: $option";
	if [ -z "$processor" ]; then
		processor=0
	fi
	
	freq=$(getCurrentFrequency "-c $processor")
	governor=$(getCurrentGovernor "-c $processor")
	min=$(getMinFrequency "-c $processor")
	max=$(getMaxFrequency "-c $processor")
	
	if [ "$option" == "governor" ]; then
		printf "CPU$processor:\t$governor\n";
	elif [ "$option" == "min" ]; then
		printf "CPU$processor:\t$min\n";
	elif [ "$option" == "max" ]; then
		printf "CPU$processor:\t$max\n";
	elif [ "$option" == "frequency" ]; then
		printf "CPU$processor:\t$freq\n";
	else
		printf "CPU$processor:\tgovernor $governor\tmin $min\tmax $max\tcurrent $freq\n";
	fi
}

if [ "$SET" == "YES" ]; then
	# Make sure only root can run our script to set things
	if (( $EUID != 0 )); then
	   echo "This script must be run as root if you want to change things" 1>&2
	   exit 2
	fi
	
	#we can set all of the settings being passed - governor, min, max for a specific CPU or for all
	cmdline=
	if [ ! -z "$GOVERNOR" ]; then
		cmdline="$cmdline -g '$GOVERNOR'"
	fi
	if [ ! -z "$MIN" ]; then
		cmdline="$cmdline -d ${MIN}000"
	fi
	if [ ! -z "$MAX" ]; then
		cmdline="$cmdline -u ${MAX}000"
	fi
	
	if [ -z "$QUIET" ]; then
		echo "CPU settings before:"
		#print settings before
		if [ -z "$CPU" ]; then
			#iterate through all CPUs
			totalCPUs=`grep processor /proc/cpuinfo | wc -l`
			for((cpu=0; cpu<$totalCPUs; cpu++));
			do
				list "$cpu" ""
			done
		else
			list "$CPU" ""
		fi
	fi
	#make the changes
	if [ -z "$CPU" ]; then
		#iterate through all CPUs
		totalCPUs=`grep processor /proc/cpuinfo | wc -l`
		for((cpu=0; cpu<$totalCPUs; cpu++));
		do
			sudo su -c "$cpuset -c $cpu $cmdline"
		done
	else
		sudo su -c "$cpuset -c $CPU $cmdline"
	fi
	
	if [ -z "$QUIET" ]; then
		echo "CPU settings after:"
		#print settings after
		if [ -z "$CPU" ]; then
			#iterate through all CPUs
			totalCPUs=`grep processor /proc/cpuinfo | wc -l`
			cpu=0;
			for((cpu=0; cpu<$totalCPUs; cpu++));
			do
				list "$cpu" ""
			done
		else
			list "$CPU" ""
		fi
	fi
	
elif [ "$LIST" == "YES" ]; then
	#we call cpufreq-info and parse out the results
	
	opts=""
	if [ ! -z "$GOVERNOR" ]; then
		opts='governor'
	elif [ ! -z "$MIN" ]; then
		opts='min'
	elif [ ! -z "$MAX" ]; then
		opts='max'
	elif [ "$FREQUENCY" == "YES" ]; then
		opts='frequency'
	else
		opts=''
	fi
	
	if [ -z "$CPU" ]; then
		#iterate through all CPUs
		totalCPUs=`grep processor /proc/cpuinfo | wc -l`
		for((cpu=0; cpu<$totalCPUs; cpu++));
		do
			list "$cpu" "$opts"
		done
	else
		list "$CPU" "$opts"
	fi
else 
	usage
	exit 1;
fi
